
name: GitHub Actions Check

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3003081@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      
